af_unix: Replace unix_table_lock with per-hash locks v3
see: https://lore.kernel.org/all/20211124021431.48956-1-kuniyu@amazon.co.jp/

Squashed commit of the following:

commit 1ee0a29e7d84c2a3c0392c5a3829632ca1be9090
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:31 2021 +0900

    af_unix: Relax race in unix_autobind().

    When we bind an AF_UNIX socket without a name specified, the kernel selects
    an available one from 0x00000 to 0xFFFFF.  unix_autobind() starts searching
    from a number in the 'static' variable and increments it after acquiring
    two locks.

    If multiple processes try autobind, they obtain the same lock and check if
    a socket in the hash list has the same name.  If not, one process uses it,
    and all except one end up retrying the _next_ number (actually not, it may
    be incremented by the other processes).  The more we autobind sockets in
    parallel, the longer the latency gets.  We can avoid such a race by
    searching for a name from a random number.

    These show latency in unix_autobind() while 64 CPUs are simultaneously
    autobind-ing 1024 sockets for each.

      Without this patch:

         usec          : count     distribution
            0          : 1176     |***                                     |
            2          : 3655     |***********                             |
            4          : 4094     |*************                           |
            6          : 3831     |************                            |
            8          : 3829     |************                            |
            10         : 3844     |************                            |
            12         : 3638     |***********                             |
            14         : 2992     |*********                               |
            16         : 2485     |*******                                 |
            18         : 2230     |*******                                 |
            20         : 2095     |******                                  |
            22         : 1853     |*****                                   |
            24         : 1827     |*****                                   |
            26         : 1677     |*****                                   |
            28         : 1473     |****                                    |
            30         : 1573     |*****                                   |
            32         : 1417     |****                                    |
            34         : 1385     |****                                    |
            36         : 1345     |****                                    |
            38         : 1344     |****                                    |
            40         : 1200     |***                                     |

      With this patch:

         usec          : count     distribution
            0          : 1855     |******                                  |
            2          : 6464     |*********************                   |
            4          : 9936     |********************************        |
            6          : 12107    |****************************************|
            8          : 10441    |**********************************      |
            10         : 7264     |***********************                 |
            12         : 4254     |**************                          |
            14         : 2538     |********                                |
            16         : 1596     |*****                                   |
            18         : 1088     |***                                     |
            20         : 800      |**                                      |
            22         : 670      |**                                      |
            24         : 601      |*                                       |
            26         : 562      |*                                       |
            28         : 525      |*                                       |
            30         : 446      |*                                       |
            32         : 378      |*                                       |
            34         : 337      |*                                       |
            36         : 317      |*                                       |
            38         : 314      |*                                       |
            40         : 298      |                                        |

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 6e8cb0f31a1857cbb990f5baecfc4ad37f0dbe1c
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:30 2021 +0900

    af_unix: Replace the big lock with small locks.

    The hash table of AF_UNIX sockets is protected by the single lock.  This
    patch replaces it with per-hash locks.

    The effect is noticeable when we handle multiple sockets simultaneously.
    Here is a test result on an EC2 c5.24xlarge instance.  It shows latency
    (under 10us only) in unix_insert_unbound_socket() while 64 CPUs creating
    1024 sockets for each in parallel.

      Without this patch:

         nsec          : count     distribution
            0          : 179      |                                        |
            500        : 3021     |*********                               |
            1000       : 6271     |*******************                     |
            1500       : 6318     |*******************                     |
            2000       : 5828     |*****************                       |
            2500       : 5124     |***************                         |
            3000       : 4426     |*************                           |
            3500       : 3672     |***********                             |
            4000       : 3138     |*********                               |
            4500       : 2811     |********                                |
            5000       : 2384     |*******                                 |
            5500       : 2023     |******                                  |
            6000       : 1954     |*****                                   |
            6500       : 1737     |*****                                   |
            7000       : 1749     |*****                                   |
            7500       : 1520     |****                                    |
            8000       : 1469     |****                                    |
            8500       : 1394     |****                                    |
            9000       : 1232     |***                                     |
            9500       : 1138     |***                                     |
            10000      : 994      |***                                     |

      With this patch:

         nsec          : count     distribution
            0          : 1634     |****                                    |
            500        : 13170    |****************************************|
            1000       : 13156    |*************************************** |
            1500       : 9010     |***************************             |
            2000       : 6363     |*******************                     |
            2500       : 4443     |*************                           |
            3000       : 3240     |*********                               |
            3500       : 2549     |*******                                 |
            4000       : 1872     |*****                                   |
            4500       : 1504     |****                                    |
            5000       : 1247     |***                                     |
            5500       : 1035     |***                                     |
            6000       : 889      |**                                      |
            6500       : 744      |**                                      |
            7000       : 634      |*                                       |
            7500       : 498      |*                                       |
            8000       : 433      |*                                       |
            8500       : 355      |*                                       |
            9000       : 336      |*                                       |
            9500       : 284      |                                        |
            10000      : 243      |                                        |

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 59e4b2ef18bc14c5f5b4f49b7dad5deec5aace58
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:29 2021 +0900

    af_unix: Save hash in sk_hash.

    To replace unix_table_lock with per-hash locks in the next patch, we need
    to save a hash in each socket because /proc/net/unix or BPF prog iterate
    sockets while holding a hash table lock and release it later in a different
    function.

    Currently, we store a real/pseudo hash in struct unix_address.  However, we
    do not allocate it to unbound sockets, nor should we do just for that.  For
    this purpose, we can use sk_hash.  Then, we no longer use the hash field in
    struct unix_address and can remove it.

    Also, this patch does
      - rename unix_insert_socket() to unix_insert_unbound_socket()
      - remove the redundant list argument from __unix_insert_socket() and
         unix_insert_unbound_socket()
      - use 'unsigned int' instead of 'unsigned' in __unix_set_addr_hash()
      - remove 'inline' from unix_remove_socket() and
         unix_insert_unbound_socket().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 7b723a743faa8a5534b05566786301ebebb043ba
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:28 2021 +0900

    af_unix: Add helpers to calculate hashes.

    This patch adds three helper functions that calculate hashes for unbound
    sockets and bound sockets with BSD/abstract addresses.

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 161596cdc0b6965890aa397c5bd4cd7a86a0d400
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:27 2021 +0900

    af_unix: Remove UNIX_ABSTRACT() macro and test sun_path[0] instead.

    In BSD and abstract address cases, we store sockets in the hash table with
    keys between 0 and UNIX_HASH_SIZE - 1.  However, the hash saved in a socket
    varies depending on its address type; sockets with BSD addresses always
    have UNIX_HASH_SIZE in their unix_sk(sk)->addr->hash.

    This is just for the UNIX_ABSTRACT() macro used to check the address type.
    The difference of the saved hashes comes from the first byte of the address
    in the first place.  So, we can test it directly.

    Then we can keep a real hash in each socket and replace unix_table_lock
    with per-hash locks in the later patch.

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 237d5ec9f584ec69c1dbfd20106076adf9e483d3
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:26 2021 +0900

    af_unix: Allocate unix_address in unix_bind_(bsd|abstract)().

    To terminate address with '\0' in unix_bind_bsd(), we add
    unix_create_addr() and call it in unix_bind_bsd() and unix_bind_abstract().

    Also, unix_bind_abstract() does not return -EEXIST.  Only
    kern_path_create() and vfs_mknod() in unix_bind_bsd() can return it,
    so we move the last error check in unix_bind() to unix_bind_bsd().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 2f98fa0b3b63e8d10d1022491e331a7f05479ae9
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:25 2021 +0900

    af_unix: Remove unix_mkname().

    This patch removes unix_mkname() and postpones calculating a hash to
    unix_bind_abstract().  Some BSD stuffs still remain in unix_bind()
    though, the next patch packs them into unix_bind_bsd().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 0a0c8192a4b8a56d07b7686a01e27dd73e12e351
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:24 2021 +0900

    af_unix: Copy unix_mkname() into unix_find_(bsd|abstract)().

    We should not call unix_mkname() before unix_find_other() and instead do
    the same thing where necessary based on the address type:

      - terminating the address with '\0' in unix_find_bsd()
      - calculating the hash in unix_find_abstract().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 061f2f340fc35259771e469762b39efbae7f21f9
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:23 2021 +0900

    af_unix: Cut unix_validate_addr() out of unix_mkname().

    unix_mkname() tests socket address length and family and does some
    processing based on the address type.  It is called in the early stage,
    and therefore some instructions are redundant and can end up in vain.

    The address length/family tests are done twice in unix_bind().  Also, the
    address type is rechecked later in unix_bind() and unix_find_other(), where
    we can do the same processing.  Moreover, in the BSD address case, the hash
    is set to 0 but never used and confusing.

    This patch moves the address tests out of unix_mkname(), and the following
    patches move the other part into appropriate places and remove
    unix_mkname() finally.

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit b4365eac7e478d826d1d62e8144cac3b5d894c5e
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:22 2021 +0900

    af_unix: Return an error as a pointer in unix_find_other().

    We can return an error as a pointer and need not pass an additional
    argument to unix_find_other().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit db43d103e5a3399b23e53076edc1f4b0aaa960c0
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:21 2021 +0900

    af_unix: Factorise unix_find_other() based on address types.

    As done in the commit fa42d910a38e ("unix_bind(): take BSD and abstract
    address cases into new helpers"), this patch moves BSD and abstract address
    cases from unix_find_other() into unix_find_bsd() and unix_find_abstract().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 15b2298c71e248fd7ff8b524e42dd0b99d968cc6
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:20 2021 +0900

    af_unix: Pass struct sock to unix_autobind().

    We do not use struct socket in unix_autobind() and pass struct sock to
    unix_bind_bsd() and unix_bind_abstract().  Let's pass it to unix_autobind()
    as well.

    Also, this patch fixes these errors by checkpatch.pl.

      ERROR: do not use assignment in if condition
      #1795: FILE: net/unix/af_unix.c:1795:
      +	if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr

      CHECK: Logical continuations should be on the previous line
      #1796: FILE: net/unix/af_unix.c:1796:
      +	if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr
      +	    && (err = unix_autobind(sock)) != 0)

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>

commit 899b11ff205f78fa78cd4070e905486f07cc709f
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:19 2021 +0900

    af_unix: Use offsetof() instead of sizeof().

    The length of the AF_UNIX socket address contains an offset to the member
    sun_path of struct sockaddr_un.

    Currently, the preceding member is just sun_family, and its type is
    sa_family_t and resolved to short.  Therefore, the offset is represented by
    sizeof(short).  However, it is not clear and fragile to changes in struct
    sockaddr_storage or sockaddr_un.

    This commit makes it clear and robust by rewriting sizeof() with
    offsetof().

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>